runtime: python39

env_variables:
  OPENAI_API_KEY: "your-openai-api-key-here"

automatic_scaling:
  min_instances: 0
  max_instances: 10
  target_cpu_utilization: 0.6

resources:
  cpu: 1
  memory_gb: 1
  disk_size_gb: 10

handlers:
- url: /.*
  script: auto
  secure: always